### ISSUE TITLE
Profile removes email

### ISSUE THREAD

**Issue by joshuawilson** [fabric8io/fabric8-ui#1386]
I went into my profile and edited it. I updated the bio. Then I logged out and tried to log back in. My email was removed from my profile and I could not access my account.

**Comment by alexeykazakov** [comment]
We will also make sure our API doesn't allow to remove emails - https://github.com/almighty/almighty-core/issues/1340

**Comment by dlabrecq** [comment]
I couldn't reproduce the issue -- my email is still available. However, the UI does allow the email to be removed. If the input field changed to an empty string, the email will be deleted when updating the profile.

That said, I made the email required. It can still be changed, but not removed. I also cleaned up some empty profile properties, which may be added when profile attributes are not available. The user should be able to change/remove other properties such as their bio, company, etc.

https://github.com/fabric8io/fabric8-ui/pull/1394

**Comment by alexeykazakov** [comment]
Maybe you couldn't reproduce it because https://github.com/almighty/almighty-core/issues/1340 has been already fixed.

**Comment by dlabrecq** [comment]
Possibly, but I've tested this page quit a bit. Changed my bio, full name, etc., but never tried an empty string for the email. Still not quite sure how Joshua removed his email?
