### ISSUE TITLE
UI does not recognize accounts already linked

### ISSUE THREAD

**Issue by xcoulon** [fabric8io/fabric8-ui#809]
As a user, when logging in, I'm brought to a page that asks me to connect my github and openshift accounts. Once this is done, if I try to login again, I arrive again on this same page even though the linking as been recorded (as verified on the `Federated Identities` pages of the KC console).

**Comment by dlabrecq** [comment]
If you log in without a linked account, you are brought to the getting started page. After you link the accounts, you are intentionally returned to the getting started page, but this time there is a success message. You are expected to click the "Get Started" button or one of the home/profile page links. 

The workflow can be viewed here:
https://redhat.invisionapp.com/share/KQB6LEHM8#/screens/227580194

To test, first log out completely. Remove the linked accounts from keycloak. Revoke "Prod-preview Openshift.io" from the authorized applications on GitHub.

**Comment by dlabrecq** [comment]
The way the page determines success is if it can obtain a GitHub and OpenShift token. You can check if they have been linked here (may need to log in, again):
https://sso.prod-preview.openshift.io/auth/realms/fabric8/account/identity

**Comment by xcoulon** [comment]
yes, I've see the GitHub and OpenShift accounts linked on the Keycloak admin console, but I was sent back to the getting started page without any success message to continue.

**Comment by dlabrecq** [comment]
It appears that the Rxjs Observable.combineLatest is not obtaining both GitHub and OpenShift tokens reliably. We need to test both tokens in order to navigate to home page or show getting started page.

Fixed by:
https://github.com/fabric8io/fabric8-ui/pull/827

**Comment by xcoulon** [comment]
@dlabrecq I'm reopening the issue since I still have the same problem, where I get back to the registration page without any success message.

**Comment by rkratky** [comment]
Not sure if this is related, but even after linking GH and OS accounts (and they show on the KC Console page under "Federated Identities"), when I click on "Update Profile" on the profile page on os.io, It tells me:

*Please connect your GitHub and OpenShift accounts to OpenShit.io.*

Clicking on the respective buttons (Connect GitHub account, Connect OpenShift account) doesn't do anything, and the "Update Profile" button stays grayed out, so it's impossible to save any profile changes (such as e-mail address or name).

**Comment by dlabrecq** [comment]
The functionality on the edit profile page has not been implemented. The rest has been fixed.
